name: Hello World Workflow

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Dire Bonjour
        run: echo "Hello World!"

      - name: Afficher la date actuelle
        run: date

      - name: Afficher le contenu du répertoire
        run: ls -lah